# Generated by Django 3.1.3 on 2021-04-29 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='LineUserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='表示名')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.line')),
            ],
        ),
    ]
