version: '3'
 
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt:ro
      - ./nginx/uwsgi_params:/code
      - ../garbageday_management/static:/static
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - web
  web:
    build: web/.
    container_name: garbageday_management
    expose:
      - '8001'
    volumes:
      - ../garbageday_management:/code
      - logs:/var/log
    command:  uwsgi --socket :8001 --module garbageday_management.wsgi --threads 1
    depends_on:
      - db  
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
  dbdata:
    external: true
  logs:
    external: true

